//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiKala.Model.DomainModel.DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DigiKalaEntities : DbContext
    {
        public DigiKalaEntities()
            : base("name=DigiKalaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
    
        public virtual int usp_Create_Category_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Create_Category_Table");
        }
    
        public virtual ObjectResult<usp_Select_Category_Result> usp_Select_Category()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_Category_Result>("usp_Select_Category");
        }
    }
}
